name: Star Thank You

on:
  watch:  # This event triggers when a repository is starred
    types: [started]

jobs:
  thank_you:
    runs-on: ubuntu-latest
    steps:
      - name: Thank the user
        uses: actions/github-script@v3
        with:
          script: |
            const user = context.payload.sender.login;
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Thank you, @${user}!`,
              body: `🎉 Thanks for starring this repository, @${user}! Your support means a lot.`
            });
